/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PotdRouteImport } from './routes/potd'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourceIndexRouteImport } from './routes/resource/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ResourceSlugRouteImport } from './routes/resource/$slug'
import { Route as ProfileSlugRouteImport } from './routes/profile/$slug'
import { Route as LeaderboardSlugRouteImport } from './routes/leaderboard/$slug'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as EventsSlugIndexRouteImport } from './routes/events/$slug/index'
import { Route as EventsLeaderboardSlugRouteImport } from './routes/events/leaderboard.$slug'
import { Route as EventsSlugAdminRouteImport } from './routes/events/$slug/admin'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PotdRoute = PotdRouteImport.update({
  id: '/potd',
  path: '/potd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIndexRoute = ResourceIndexRouteImport.update({
  id: '/resource/',
  path: '/resource/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceSlugRoute = ResourceSlugRouteImport.update({
  id: '/resource/$slug',
  path: '/resource/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSlugRoute = ProfileSlugRouteImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardSlugRoute = LeaderboardSlugRouteImport.update({
  id: '/leaderboard/$slug',
  path: '/leaderboard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsSlugRoute,
} as any)
const EventsLeaderboardSlugRoute = EventsLeaderboardSlugRouteImport.update({
  id: '/events/leaderboard/$slug',
  path: '/events/leaderboard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugAdminRoute = EventsSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => EventsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/potd': typeof PotdRoute
  '/stats': typeof StatsRoute
  '/wrapped': typeof WrappedRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/leaderboard/$slug': typeof LeaderboardSlugRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/resource/$slug': typeof ResourceSlugRoute
  '/events': typeof EventsIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resource': typeof ResourceIndexRoute
  '/events/$slug/admin': typeof EventsSlugAdminRoute
  '/events/leaderboard/$slug': typeof EventsLeaderboardSlugRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/potd': typeof PotdRoute
  '/stats': typeof StatsRoute
  '/wrapped': typeof WrappedRoute
  '/leaderboard/$slug': typeof LeaderboardSlugRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/resource/$slug': typeof ResourceSlugRoute
  '/events': typeof EventsIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/resource': typeof ResourceIndexRoute
  '/events/$slug/admin': typeof EventsSlugAdminRoute
  '/events/leaderboard/$slug': typeof EventsLeaderboardSlugRoute
  '/events/$slug': typeof EventsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/potd': typeof PotdRoute
  '/stats': typeof StatsRoute
  '/wrapped': typeof WrappedRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/leaderboard/$slug': typeof LeaderboardSlugRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/resource/$slug': typeof ResourceSlugRoute
  '/events/': typeof EventsIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/resource/': typeof ResourceIndexRoute
  '/events/$slug/admin': typeof EventsSlugAdminRoute
  '/events/leaderboard/$slug': typeof EventsLeaderboardSlugRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/potd'
    | '/stats'
    | '/wrapped'
    | '/events/$slug'
    | '/leaderboard/$slug'
    | '/profile/$slug'
    | '/resource/$slug'
    | '/events'
    | '/leaderboard'
    | '/profile'
    | '/resource'
    | '/events/$slug/admin'
    | '/events/leaderboard/$slug'
    | '/events/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/potd'
    | '/stats'
    | '/wrapped'
    | '/leaderboard/$slug'
    | '/profile/$slug'
    | '/resource/$slug'
    | '/events'
    | '/leaderboard'
    | '/profile'
    | '/resource'
    | '/events/$slug/admin'
    | '/events/leaderboard/$slug'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/potd'
    | '/stats'
    | '/wrapped'
    | '/events/$slug'
    | '/leaderboard/$slug'
    | '/profile/$slug'
    | '/resource/$slug'
    | '/events/'
    | '/leaderboard/'
    | '/profile/'
    | '/resource/'
    | '/events/$slug/admin'
    | '/events/leaderboard/$slug'
    | '/events/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PotdRoute: typeof PotdRoute
  StatsRoute: typeof StatsRoute
  WrappedRoute: typeof WrappedRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  LeaderboardSlugRoute: typeof LeaderboardSlugRoute
  ProfileSlugRoute: typeof ProfileSlugRoute
  ResourceSlugRoute: typeof ResourceSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ResourceIndexRoute: typeof ResourceIndexRoute
  EventsLeaderboardSlugRoute: typeof EventsLeaderboardSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potd': {
      id: '/potd'
      path: '/potd'
      fullPath: '/potd'
      preLoaderRoute: typeof PotdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/': {
      id: '/resource/'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof ResourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$slug': {
      id: '/resource/$slug'
      path: '/resource/$slug'
      fullPath: '/resource/$slug'
      preLoaderRoute: typeof ResourceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$slug': {
      id: '/leaderboard/$slug'
      path: '/leaderboard/$slug'
      fullPath: '/leaderboard/$slug'
      preLoaderRoute: typeof LeaderboardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/events/leaderboard/$slug': {
      id: '/events/leaderboard/$slug'
      path: '/events/leaderboard/$slug'
      fullPath: '/events/leaderboard/$slug'
      preLoaderRoute: typeof EventsLeaderboardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/admin': {
      id: '/events/$slug/admin'
      path: '/admin'
      fullPath: '/events/$slug/admin'
      preLoaderRoute: typeof EventsSlugAdminRouteImport
      parentRoute: typeof EventsSlugRoute
    }
  }
}

interface EventsSlugRouteChildren {
  EventsSlugAdminRoute: typeof EventsSlugAdminRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugAdminRoute: EventsSlugAdminRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PotdRoute: PotdRoute,
  StatsRoute: StatsRoute,
  WrappedRoute: WrappedRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  LeaderboardSlugRoute: LeaderboardSlugRoute,
  ProfileSlugRoute: ProfileSlugRoute,
  ResourceSlugRoute: ResourceSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ResourceIndexRoute: ResourceIndexRoute,
  EventsLeaderboardSlugRoute: EventsLeaderboardSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
